module:
  access_unpublished: 0
  acquia_connector: 0
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  components: 0
  config: 0
  config_log: 0
  contextual: 0
  crazyegg: 0
  ctools: 0
  datalayer: 0
  datetime: 0
  dblog: 0
  devel: 0
  draggableviews: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  encrypt: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_tokens: 0
  field_ui: 0
  file: 0
  file_browser: 0
  filter: 0
  flood_unblock: 0
  ga_login: 0
  google_map_field: 0
  google_tag: 0
  help: 0
  history: 0
  image: 0
  imagick: 0
  inline_form_errors: 0
  key: 0
  kint: 0
  libraries: 0
  link: 0
  mass_content: 0
  mass_entityreference: 0
  mass_feedback_form: 0
  mass_formatters: 0
  mass_map: 0
  mass_nav: 0
  mass_search: 0
  mass_search_suppression: 0
  mass_styles: 0
  mass_types: 0
  mass_utility: 0
  mass_validation: 0
  mass_workbench_ui: 0
  mayflower: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  migrate: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  node: 0
  options: 0
  paragraphs: 0
  password_policy: 0
  password_policy_characters: 0
  password_policy_length: 0
  path: 0
  rabbit_hole: 0
  rdf: 0
  redirect: 0
  rest: 0
  restrict_by_ip: 0
  restui: 0
  rh_taxonomy: 0
  rh_node: 0
  seckit: 0
  security_review: 0
  serialization: 0
  shortcut: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  tfa: 0
  token: 0
  toolbar: 0
  twig_field_value: 0
  twig_tweak: 0
  update: 0
  user: 0
  username_enumeration_prevention: 0
  views_ui: 0
  workbench_moderation: 0
  workbench_tabs: 0
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  views: 10
theme:
  stable: 0
  classy: 0
  bartik: 0
  mass_theme: 0
  seven: 0
  mass_admin_theme: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
